const A='./assets/source/';
const cards=[
{id:'cover-a',layout:'cover',part:'上篇 01/11',k:'10 DAYS · 4 CITIES · PART 1',img:'00-hero.jpg',html:`<div class="title-stack"><div class="line-1">第一次去云南</div><div class="line-2">10天这样走</div><div class="line-3">先低后高，不赶路</div><p class="route-note">昆明 2天 → 大理 3天｜完整攻略上篇：DAY 1—5</p></div>`},
{id:'route',layout:'route',part:'上篇 02/11',k:'ROUTE / ALTITUDE / TRANSFER',title:'先把海拔<br>走成一条缓坡',deck:'顺序不是装饰：它决定身体适应、交通衔接和每天能装多少内容。'},
{id:'kunming-base',layout:'split',part:'上篇 03/11',k:'KUNMING / ARRIVAL',title:'昆明先落地<br><span class="accent">再适应</span>',deck:'DAY 1 不把行程排满。昆明是后面高海拔路线的缓冲区。',img:'01-kunming-overview.webp'},
{id:'stone-forest',layout:'branches',part:'上篇 04/11',k:'KUNMING / ROUTE CHOICE',title:'石林不是一个点<br>而是三种走法',deck:'先分清主线、避人群与加码，再决定一天的体力怎么用。',img:'02-stone-forest.webp'},
{id:'green-lake',layout:'orbit',part:'上篇 05/11',k:'KUNMING / TIME CONDITION',title:'翠湖值不值得去<br>关键看<span class="accent">时间条件</span>',deck:'同一个地点，因为季节和星期不同，会变成完全不同的体验。',img:'03-green-lake.webp'},
{id:'kunming-choices',layout:'index',part:'上篇 06/11',k:'KUNMING / FILTER',title:'昆明备选<br>按兴趣筛，不按数量塞',deck:'两天装不下全部景点。先选兴趣，再让住宿服务第二天的出发方向。'},
{id:'dali-base',layout:'timeline',part:'上篇 07/11',k:'DALI / 3-DAY STRUCTURE',title:'大理三天<br>古迹、文化、湖边分开走',deck:'昆明到大理高铁约 2.5h；海拔约 2,000m。三个主题各占一天，行程才不会互相挤压。',img:'07-dali-overview.webp'},
{id:'three-pagodas',layout:'evidence',part:'上篇 08/11',k:'DALI / HISTORY + TIME',title:'三塔<br>从历史看到<span class="accent">亮灯</span>',deck:'它不是“拍完就走”的地标：建筑细节、寺院范围与日落时间共同决定体验。',img:'08-three-pagodas.webp'},
{id:'xizhou',layout:'path',part:'上篇 09/11',k:'DALI / CULTURE WALK',title:'喜洲<br>别只去麦田拍照',deck:'先沿一条白族文化线走完，再把取景地、田野和咖啡馆当作第二层体验。',img:'09-xizhou.webp'},
{id:'erhai',layout:'lake',part:'上篇 10/11',k:'DALI / MODE + STOPS',title:'洱海先选玩法<br>再选沿湖停靠点',deck:'一整天不是围着湖赶点，而是先决定怎么移动，再挑最匹配的停靠。',img:'10-erhai.webp'},
{id:'dali-more',layout:'matrix',part:'上篇 11/11',k:'DALI / CHOOSE + STAY',title:'大理最后一页<br>把备选与住宿收好',deck:'备选不是“全部追加”；住宿也不是景点，要服务你真正选下来的三天动线。'},
{id:'cover-b',layout:'full',part:'下篇 01/11',k:'DAY 6—10 · PART 2',title:'从丽江到香格里拉<br><span class="accent">雪山、峡谷与高海拔</span>',deck:'后半程的核心不是“更多景点”，而是票务、体力与风险管理。',img:'15-jade-dragon.webp'},
{id:'lijiang-base',layout:'days',part:'下篇 02/11',k:'LIJIANG / TWO DAYS',title:'丽江两天<br>古城与雪山各留一天',deck:'大理到丽江高铁约 1h45；海拔约 2,400m。城市慢走与高山行程不要混排。'},
{id:'lijiang-old-town',layout:'walk',part:'下篇 03/11',k:'LIJIANG / WALKING THREAD',title:'丽江古城<br>地图可以先收起来',deck:'用空间线索而不是打卡清单：一路漫游，但给同行者留一个确定的集合点。',img:'14-lijiang-old-town.webp'},
{id:'jade-dragon',layout:'nested',part:'下篇 04/11',k:'LIJIANG / MOUNTAIN SYSTEM',title:'玉龙雪山<br>路径、票务、替代一起准备',deck:'这一天是一个嵌套系统：山脚适应、高处主线、低强度替代，缺一层都会临时被动。',img:'15-jade-dragon.webp'},
{id:'lijiang-more',layout:'choices',part:'下篇 05/11',k:'LIJIANG / OPTIONAL',title:'丽江备选<br>分清“加选”与“延长线”',deck:'黑龙潭可以塞进城市空档；雨崩 5 日徒步是另一段完整旅程。住宿按古城步行与雪山出发来选。'},
{id:'shangri-base',layout:'altitude',part:'下篇 06/11',k:'SHANGRI-LA / ARRIVAL',title:'香格里拉<br>最高点，要给身体留余量',deck:'高铁约 1h20。到 3,100m 后，抵达日的留白本身就是行程设计。',img:'19-shangrila-overview.webp'},
{id:'songzanlin',layout:'arrival',part:'下篇 07/11',k:'SHANGRI-LA / ACCESS',title:'松赞林寺<br>先选怎么到，再算体力',deck:'巴士与沿湖步行是两种入口；147 级台阶是进入核心区前必须预留的体力。',img:'20-songzanlin.webp'},
{id:'balagezong',layout:'system',part:'下篇 08/11',k:'SHANGRI-LA / FULL DAY',title:'巴拉格宗<br>是一条完整的一日游',deck:'自然、文化与高空项目层层嵌套，不要再和虎跳峡硬塞在同一天。',img:'21-balagzong.webp'},
{id:'tiger-leaping',layout:'risk',part:'下篇 09/11',k:'SHANGRI-LA / ROUTE + RISK',title:'虎跳峡<br>先选路线，再谈能不能走',deck:'17km、近 4,000m 深。时长、难度与雨季风险必须一起判断。',img:'23-tiger-leaping-2.webp'},
{id:'shangri-choices',layout:'matrix2',part:'下篇 10/11',k:'SHANGRI-LA / CHOOSE + STAY',title:'最后的备选<br>按体力、天气和集合动线选',deck:'纳帕海、普达措是加选；住宿优先服务高海拔抵达日与一日游集合。',img:'24-shangrila-highlights.webp'},
{id:'final',layout:'check',part:'下篇 11/11',k:'RETURN / FINAL CHECK',title:'返程前<br>把所有可变信息再查一遍',deck:'原文建议香格里拉飞回昆明约 1h；价格与班次随日期变化。',img:'25-shangrila-hotels.webp'}
];
const photo=(c,cls='wide')=>`<figure class="photo ${cls}"><img src="${A+c.img}" alt="${c.title?.replace(/<[^>]+>/g,'')||'云南路线'}相关的 Klook 原文图片"><figcaption>图片：Klook 原文｜原署名见来源页</figcaption></figure>`;
const frame=(c,body,extra='')=>`<section id="card-${c.id}" class="card ${extra}" data-qs-frame="${c.id}" data-qs-slide="${c.id}" aria-label="${c.part} ${c.title?.replace(/<[^>]+>/g,'')||'封面'}"><header class="head"><span class="kicker">${c.k}</span><span class="folio">${c.part}</span></header>${body}<footer class="footer"><span class="source">据 Klook《给旅游新手的云南10天行程推荐》整理｜信息以出发日前为准</span><span class="part">QUIET SIGNAL</span></footer></section>`;
function render(c){let b='';switch(c.layout){
case'cover':b=`${c.html}${photo(c,'wide')}`;return frame(c,b,'hero-cover');
case'route':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="route-rail"><div class="altitudes"><div class="alt">LOW<b>1,890m</b></div><div class="alt">HIGH<b>3,100m</b></div></div><div class="route-stops"><div class="stop"><span class="day">DAY 1—2</span><strong>昆明</strong><small>起点</small></div><div class="stop"><span class="day">DAY 3—5</span><strong>大理</strong><small>高铁约 2.5h</small></div><div class="stop"><span class="day">DAY 6—7</span><strong>丽江</strong><small>约 1h45</small></div><div class="stop"><span class="day">DAY 8—10</span><strong>香格里拉</strong><small>约 1h20</small></div></div></div>`;break;
case'split':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="split-hero">${photo(c,'tall')}<div class="split-copy"><div class="stat"><b>1,890m</b><span>从低处开始适应，给后面的丽江与香格里拉留余量。</span></div><div class="stat"><b>DAY 1</b><span>长水机场进入；只做城市轻量活动，不安排远郊。</span></div><div class="stat"><b>春城</b><span>气候温和，也是原文提到的丝绸之路门户。</span></div></div></div>`;break;
case'branches':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="branches">${photo(c,'wide')}<div class="branch-list"><div class="branch primary"><b>主线</b><p>大石林 + 小石林；小石林找“阿诗玛”岩石。</p></div><div class="branch"><b>避人群</b><p>同一区域转去乃古石林。</p></div><div class="branch"><b>体力加码</b><p>约 40 分钟巴士去九乡溶洞，看 100 多个岩溶景观。</p></div></div></div>`;break;
case'orbit':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="orbit">${photo(c,'half')}<div class="orbit-node n1"><b>11月—3月</b><p>可能见到黑头鸥。</p></div><div class="orbit-node n2"><b>星期日</b><p>可能遇到传统服装与大型歌舞。</p></div><div class="orbit-node n3"><b>慢下来</b><p>亭台、湖面与绿廊本身就是体验。</p></div><div class="orbit-node n4"><b>别写死</b><p>季节与活动情况出发前复核。</p></div></div>`;break;
case'index':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="index-grid"><div class="index-cell"><span class="tag">OLD CITY</span><b>城市文化</b><p>昆明老街、云南民族村</p></div><div class="index-cell"><span class="tag">FAMILY</span><b>亲子娱乐</b><p>七彩云南欢乐世界、融创海世界</p></div><div class="index-cell"><span class="tag">NATURE</span><b>自然景观</b><p>西山龙门、翠湖公园</p></div><div class="index-cell"><span class="tag">LONG RANGE</span><b>远郊风景</b><p>东川红土地；单独核算往返时间</p></div></div><div class="stay-strip"><b>住宿判断：</b>按机场 / 市区动线与第二天去大理的出发方向复核。</div>`;break;
case'timeline':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="timeline"><div class="time-node"><b>DAY 3</b><p>崇圣寺三塔<br>看古迹与日落</p></div><div class="time-node"><b>DAY 4</b><p>喜洲古镇<br>读白族文化</p></div><div class="time-node"><b>DAY 5</b><p>洱海<br>留一整天</p></div></div>${photo(c,'timeline-photo')}`;break;
case'evidence':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="evidence-stage">${photo(c,'tall')}<div class="evidence-copy"><div class="evidence-card"><b>公元 10 世纪</b><p>一大两小，呈对称三角形；历经多次地震仍屹立。</p></div><div class="evidence-card"><b>抬头看</b><p>千寻塔顶金鸟，原文解释为抵御邪恶水灵。</p></div><div class="evidence-card key"><b>日落前抵达</b><p>崇圣寺在塔后，占地约 4 平方公里；留到亮灯再走。</p></div></div></div>`;break;
case'path':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="path">${photo(c,'tall')}<div class="path-steps"><div class="path-step"><b>早市</b><p>从日常生活进入。</p></div><div class="path-step"><b>三道茶</b><p>认识白族待客文化。</p></div><div class="path-step"><b>严家大院</b><p>看白族建筑。</p></div><div class="path-step"><b>建筑博物馆</b><p>把结构看懂。</p></div><div class="path-step"><b>四方街 + 老木角楼</b><p>最后再转向田野与取景地。</p></div></div></div>`;break;
case'lake':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="lake-map">${photo(c,'wide')}<div class="mode-list"><div class="mode">乘船</div><div class="mode">骑行</div><div class="mode">观光车</div><div class="mode">湖边野餐</div></div></div><div class="chips"><span class="chip">双廊</span><span class="chip">挖色</span><span class="chip">大理乌托邦</span><span class="chip">南诏风情岛</span><span class="chip">小普陀岛</span><span class="chip">周城村·扎染</span></div>`;break;
case'matrix':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="matrix"><div class="cell darkcell"><b>古城</b><p>大理古城：适合城市步行与夜间氛围。</p></div><div class="cell"><b>山线</b><p>苍山：另算天气与索道 / 徒步条件。</p></div><div class="cell"><b>远郊</b><p>沙溪古镇：距离更远，不和洱海整日硬叠。</p></div><div class="cell"><b>住宿</b><p>三塔、古城、洱海三种动线，先定主线再选区域。</p></div></div><div class="stay-strip">下篇：DAY 6—10｜丽江古城、玉龙雪山、香格里拉、虎跳峡与返程。</div>`;break;
case'full':return `<section id="card-${c.id}" class="card full-cover dark" data-qs-frame="${c.id}" data-qs-slide="${c.id}" aria-label="${c.part} 下篇封面">${photo(c,'tall')}<div class="overlay"><header class="head"><span class="kicker">${c.k}</span><span class="folio">${c.part}</span></header><h1>${c.title}</h1><p class="deck">${c.deck}</p><footer class="footer"><span>据 Klook 原文整理｜所有可变信息出发前复核</span><span class="part">QUIET SIGNAL</span></footer></div></section>`;
case'days':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="day-split"><div class="day-panel"><div class="daynum">06</div><h3>古城慢走</h3><p>木府、狮子山、四方街、大研花巷；节庆日期按当年农历复核。</p><div class="mini-photo"><img src="${A}13-lijiang-overview.webp" alt="丽江古城夜景"></div></div><div class="day-panel"><div class="daynum">07</div><h3>蓝月谷 + 雪山</h3><p>高海拔日单独留出；票务、缆车与体力都要提前准备。</p><div class="mini-photo"><img src="${A}15-jade-dragon.webp" alt="玉龙雪山"></div></div></div>`;break;
case'walk':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="walk-thread"><div><div class="walk-line"><span>木府</span><span>狮子山</span><span>四方街</span><span>石桥</span><span>大研花巷</span></div><div class="meet"><b>走散怎么办？</b><br>约在标志性的巨型水车见面，给漫游留一个确定锚点。</div></div>${photo(c,'tall')}</div>`;break;
case'nested':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="nested"><div class="layer"><b>山脚层</b><p>蓝月谷轻徒步，先观察身体状态。</p></div><div class="layer"><b>高处主线</b><p>缆车到冰川公园，站点海拔约 4,506m；票务以出发日前规则为准。</p></div><div class="layer"><b>替代方案</b><p>云杉坪 / 牦牛坪；另可看《印象丽江》。</p></div></div>${photo(c,'nested-photo')}`;break;
case'choices':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="choice-bars"><div class="choice"><div class="label">城市加选</div><div class="body"><b>黑龙潭公园</b><p>可以放入丽江城市日的空档。</p></div></div><div class="choice"><div class="label">节庆条件</div><div class="body"><b>棒棒节 / 火把节</b><p>多在 2—3 月、7—8 月；日期随农历变化。</p></div></div><div class="choice"><div class="label">完整延长线</div><div class="body"><b>雨崩 5 日徒步</b><p>不能塞进丽江两天，必须另行安排。</p></div></div><div class="choice"><div class="label">住宿判断</div><div class="body"><b>古城步行 vs 雪山出发</b><p>按真正的主线选区域。</p></div></div></div>`;break;
case'altitude':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="altitude-field"><div class="big-alt"><b>3,100m</b><span>全程最高城市</span></div>${photo(c,'wide')}<div class="altitude-note"><b>抵达日原则：</b>不排满。独克宗古城约有 1,300 年历史，可作为低强度适应活动。</div></div>`;break;
case'arrival':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p>${photo(c,'half')}<div class="arrival-choice"><div class="arrival"><b>入口巴士</b><div class="time">省体力</div><p>更适合高海拔抵达后状态一般的人。</p></div><div class="arrival"><b>沿湖步行</b><div class="time">约30min</div><p>晴天无风时，更有机会看寺院湖面倒影。</p></div><div class="step-meter"><strong>147</strong><p>到顶部仍需爬 147 级台阶。看佛教宝藏与祈祷仪式前，先给身体留余量。</p></div></div>`;break;
case'system':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="system-map">${photo(c,'tall')}<div class="system-stack"><div class="system-item"><b>自然底盘</b><p>千年菩提树、香格里拉大峡谷、巴拉雪山。</p></div><div class="system-item"><b>文化识别</b><p>“神赐天然宝塔”香巴拉佛塔。</p></div><div class="system-item"><b>高空选择</b><p>玻璃观景台；刺激型可选滑索。</p></div><div class="system-item"><b>时间结论</b><p>按完整一日游安排，不与虎跳峡同日。</p></div></div></div>`;break;
case'risk':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p><div class="risk-bands"><div class="risk-band"><b>半日</b><p>只做轻量段，适合不想长距离徒步的人。</p><strong>低时间压力</strong></div><div class="risk-band"><b>一日</b><p>覆盖主要峡谷体验；多数步道标记清晰、难度适中。</p><strong>主流选择</strong></div><div class="risk-band"><b>两日</b><p>二十八弯更陡；中段天梯近乎垂直，共 170 级。</p><strong>高体力要求</strong></div></div>${photo(c,'half')}<div class="warning"><b>6—9 月：</b>滑坡风险较高。徒步尽量避开雨季，并在出发前核对天气与开放。</div>`;break;
case'matrix2':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p>${photo(c,'half')}<div class="matrix"><div class="cell darkcell"><b>纳帕海</b><p>更偏开放湿地景观；先看天气与季节。</p></div><div class="cell"><b>普达措</b><p>湖泊与森林；按体力和当日开放信息判断。</p></div><div class="cell"><b>巴拉格宗</b><p>已是完整一日游，不在备选里重复计算。</p></div><div class="cell"><b>住宿</b><p>优先服务抵达日休息与次日集合点。</p></div></div>`;break;
case'check':b=`<h2>${c.title}</h2><p class="deck">${c.deck}</p>${photo(c,'half')}<div class="check-grid"><div class="check"><b>城际交通</b><p>高铁车次与实际运行时刻</p></div><div class="check"><b>景区状态</b><p>开放、预约与临时管制</p></div><div class="check"><b>雪山票务</b><p>缆车规则与库存</p></div><div class="check"><b>徒步条件</b><p>天气、雨季与路线状态</p></div><div class="check"><b>节庆日期</b><p>按当年农历核对</p></div><div class="check"><b>返程价格</b><p>香格里拉飞昆明班次与票价</p></div></div><div class="return-strip">资料来源：Klook《给旅游新手的云南10天行程推荐》｜Amanda Ng｜页面显示更新 2025-08-22</div>`;break;}
return frame(c,b,c.layout==='risk'?'dark':'');}
document.getElementById('cards').innerHTML=cards.map(render).join('');
